plugins:
  donorbox_enabled:
    default: true
    client: true

  donorbox_access_email:
    default: ""
    client: true

  donorbox_access_key:
    default: ""
    client: true

  donorbox_url:
    default: "donorbox.org"
    client: true
